// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using digitalAgency.Persistence.Contexts;

#nullable disable

namespace digitalAgency.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121150130_user_jwt")]
    partial class user_jwt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.Property<Guid>("BlogsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogTag");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Abouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab000001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 589, DateTimeKind.Utc).AddTicks(9100),
                            Description = "2014'ten bu yana dijital pazarlama alanında hizmet veren Digital Agency, 150'den fazla markaya danışmanlık vermiş, 250'den fazla başarılı projeye imza atmıştır. SEO, sosyal medya yönetimi, Google Ads ve web tasarım konularında uzman kadromuzla işletmenizin dijital dünyadaki yolculuğuna rehberlik ediyoruz.",
                            ImageUrl = "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800",
                            IsDeleted = false,
                            Title = "Hakkımızda - Digital Agency"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(874),
                            Description = "Dijital pazarlama stratejileri ve güncel trendler hakkında bilgiler",
                            IsDeleted = false,
                            Title = "Dijital Pazarlama"
                        },
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000002"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(883),
                            Description = "Arama motoru optimizasyonu teknikleri ve ipuçları",
                            IsDeleted = false,
                            Title = "SEO"
                        },
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000003"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(888),
                            Description = "Sosyal medya yönetimi ve içerik stratejileri",
                            IsDeleted = false,
                            Title = "Sosyal Medya"
                        },
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000004"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(891),
                            Description = "Modern web tasarım trendleri ve kullanıcı deneyimi",
                            IsDeleted = false,
                            Title = "Web Tasarım"
                        },
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000005"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(895),
                            Description = "Etkili içerik üretimi ve içerik pazarlama stratejileri",
                            IsDeleted = false,
                            Title = "İçerik Pazarlama"
                        },
                        new
                        {
                            Id = new Guid("ca000001-0001-0001-0001-000000000006"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(899),
                            Description = "E-ticaret çözümleri ve online satış stratejileri",
                            IsDeleted = false,
                            Title = "E-Ticaret"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Info", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Infos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10f00001-0001-0001-0001-000000000001"),
                            Address = "Maslak Mahallesi, Büyükdere Caddesi No:123, Sarıyer/İstanbul",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(6375),
                            IsDeleted = false,
                            Mail = "info@digitalagency.com",
                            PhoneNumber = "+90 212 555 1234"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("References", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ef00001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 6, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(7765),
                            Description = "SEO ve içerik pazarlama projesi",
                            IconUrl = "https://via.placeholder.com/300x200?text=TechCorp",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "TechCorp A.Ş."
                        },
                        new
                        {
                            Id = new Guid("0ef00001-0001-0001-0001-000000000002"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(7777),
                            Description = "Sosyal medya yönetimi ve influencer marketing",
                            IconUrl = "https://via.placeholder.com/300x200?text=Fashion",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "FashionBrand"
                        },
                        new
                        {
                            Id = new Guid("0ef00001-0001-0001-0001-000000000003"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(7782),
                            Description = "Google Ads ve e-ticaret optimizasyonu",
                            IconUrl = "https://via.placeholder.com/300x200?text=ECommerce",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "E-Commerce Plus"
                        },
                        new
                        {
                            Id = new Guid("0ef00001-0001-0001-0001-000000000004"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 9, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(7786),
                            Description = "Web tasarım ve dijital pazarlama stratejisi",
                            IconUrl = "https://via.placeholder.com/300x200?text=Healthcare",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "HealthCare Solutions"
                        },
                        new
                        {
                            Id = new Guid("0ef00001-0001-0001-0001-000000000005"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 10, 21, 15, 1, 29, 590, DateTimeKind.Utc).AddTicks(7790),
                            Description = "Yerel SEO ve sosyal medya kampanyaları",
                            IconUrl = "https://via.placeholder.com/300x200?text=Restaurant",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "RestaurantChain"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(1205),
                            Description = "System Administrator",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(1210),
                            Description = "Content Editor",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Editor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(1213),
                            Description = "Regular User",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2811),
                            Description = "Google'da üst sıralarda yer alın. Organik trafiğinizi artırın ve daha fazla müşteriye ulaşın.",
                            ImageUrl = "https://images.unsplash.com/photo-1571677208715-0ca4e1d2b1b1?w=400",
                            IsDeleted = false,
                            Title = "SEO Optimizasyonu"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000002"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2823),
                            Description = "Instagram, Facebook, LinkedIn ve Twitter'da profesyonel içerik yönetimi ve strateji danışmanlığı.",
                            ImageUrl = "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400",
                            IsDeleted = false,
                            Title = "Sosyal Medya Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000003"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2828),
                            Description = "Hedef kitlenize doğrudan ulaşın. ROI odaklı reklam kampanyaları ile satışlarınızı artırın.",
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
                            IsDeleted = false,
                            Title = "Google Ads Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000004"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2832),
                            Description = "Modern, hızlı ve kullanıcı dostu web siteleri. Mobil uyumlu ve SEO optimizasyonlu.",
                            ImageUrl = "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=400",
                            IsDeleted = false,
                            Title = "Web Tasarım & Geliştirme"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000005"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2836),
                            Description = "Blog yazıları, infografikler ve video içerikleri ile markanızı güçlendirin.",
                            ImageUrl = "https://images.unsplash.com/photo-1542435503-956c469947f6?w=400",
                            IsDeleted = false,
                            Title = "İçerik Pazarlama"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000006"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(2842),
                            Description = "Online mağazanızı büyütün. Satış hunisi optimizasyonu ve pazaryeri yönetimi.",
                            ImageUrl = "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
                            IsDeleted = false,
                            Title = "E-Ticaret Danışmanlığı"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Button")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51d00001-0001-0001-0001-000000000001"),
                            Button = "Hemen Başla",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 6, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(4019),
                            Description = "Profesyonel dijital pazarlama stratejileri ile markanızı zirveye taşıyın",
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "Dijital Pazarlama ile İşinizi Büyütün"
                        },
                        new
                        {
                            Id = new Guid("51d00001-0001-0001-0001-000000000002"),
                            Button = "Detaylı Bilgi",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(4029),
                            Description = "Google'ın ilk sayfasında yer alın",
                            ImageUrl = "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c1e?w=1200",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "SEO ile Organik Trafiğinizi Artırın"
                        },
                        new
                        {
                            Id = new Guid("51d00001-0001-0001-0001-000000000003"),
                            Button = "İletişime Geç",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(4033),
                            Description = "Hedef kitlenize ulaşın",
                            ImageUrl = "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200",
                            IsDeleted = false,
                            IsShown = true,
                            Title = "Sosyal Medyada Fark Yaratın"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<string>("SocialMediaIcon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0c00001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(5422),
                            IsDeleted = false,
                            IsShown = true,
                            SocialMediaIcon = "fab fa-facebook",
                            Title = "Facebook",
                            Url = "https://facebook.com/digitalagency"
                        },
                        new
                        {
                            Id = new Guid("a0c00001-0001-0001-0001-000000000002"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(5433),
                            IsDeleted = false,
                            IsShown = true,
                            SocialMediaIcon = "fab fa-instagram",
                            Title = "Instagram",
                            Url = "https://instagram.com/digitalagency"
                        },
                        new
                        {
                            Id = new Guid("a0c00001-0001-0001-0001-000000000003"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(5438),
                            IsDeleted = false,
                            IsShown = true,
                            SocialMediaIcon = "fab fa-twitter",
                            Title = "Twitter",
                            Url = "https://twitter.com/digitalagency"
                        },
                        new
                        {
                            Id = new Guid("a0c00001-0001-0001-0001-000000000004"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(5441),
                            IsDeleted = false,
                            IsShown = true,
                            SocialMediaIcon = "fab fa-linkedin",
                            Title = "LinkedIn",
                            Url = "https://linkedin.com/company/digitalagency"
                        },
                        new
                        {
                            Id = new Guid("a0c00001-0001-0001-0001-000000000005"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(5445),
                            IsDeleted = false,
                            IsShown = true,
                            SocialMediaIcon = "fab fa-youtube",
                            Title = "YouTube",
                            Url = "https://youtube.com/@digitalagency"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000000"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6843),
                            Description = "Arama motoru optimizasyonu",
                            IsDeleted = false,
                            Title = "SEO"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6868),
                            Description = "Google reklam kampanyaları",
                            IsDeleted = false,
                            Title = "Google Ads"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000002"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6872),
                            Description = "Facebook reklam kampanyaları",
                            IsDeleted = false,
                            Title = "Facebook Ads"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000003"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6875),
                            Description = "Instagram pazarlama ve yönetimi",
                            IsDeleted = false,
                            Title = "Instagram"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000004"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6879),
                            Description = "LinkedIn profesyonel ağ pazarlaması",
                            IsDeleted = false,
                            Title = "LinkedIn"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000005"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6884),
                            Description = "İçerik pazarlama stratejileri",
                            IsDeleted = false,
                            Title = "Content Marketing"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000006"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6888),
                            Description = "E-posta pazarlama kampanyaları",
                            IsDeleted = false,
                            Title = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000007"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6891),
                            Description = "Veri analizi ve raporlama",
                            IsDeleted = false,
                            Title = "Analytics"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000008"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6894),
                            Description = "Dönüşüm optimizasyonu",
                            IsDeleted = false,
                            Title = "Conversion"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000009"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6898),
                            Description = "Kullanıcı deneyimi tasarımı",
                            IsDeleted = false,
                            Title = "UX Design"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000010"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6902),
                            Description = "Mobil pazarlama stratejileri",
                            IsDeleted = false,
                            Title = "Mobile Marketing"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000011"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6905),
                            Description = "Video içerik pazarlaması",
                            IsDeleted = false,
                            Title = "Video Marketing"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000012"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6908),
                            Description = "Influencer pazarlama kampanyaları",
                            IsDeleted = false,
                            Title = "Influencer"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000013"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6911),
                            Description = "E-ticaret çözümleri",
                            IsDeleted = false,
                            Title = "E-commerce"
                        },
                        new
                        {
                            Id = new Guid("0a600001-0001-0001-0001-000000000014"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 591, DateTimeKind.Utc).AddTicks(6914),
                            Description = "Marka kimliği ve konumlandırma",
                            IsDeleted = false,
                            Title = "Branding"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 5, 21, 15, 1, 29, 592, DateTimeKind.Utc).AddTicks(157),
                            Email = "admin@digitalagency.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "50000.Y3p0Z8vYGkW6hVvZw3x8Qg==.kYF3bZPJGZHvX2mL9sN4pQ1wR5tU8xV0yA7bC3dE6fF=",
                            PhoneNumber = "+90 555 111 1111"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 21, 15, 1, 29, 592, DateTimeKind.Utc).AddTicks(167),
                            Email = "editor@digitalagency.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            FirstName = "Editor",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "50000.bYn3Z9vYGkW7hVvZw3x9Rh==.lZG4caPKHaIwY3nM0tO5qR2xS6uV9yW1zA8cD4eF7gG=",
                            PhoneNumber = "+90 555 222 2222"
                        });
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 21, 15, 1, 29, 592, DateTimeKind.Utc).AddTicks(2649),
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000001"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 21, 15, 1, 29, 592, DateTimeKind.Utc).AddTicks(2654),
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.HasOne("digitalAgency.Domain.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("digitalAgency.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Blog", b =>
                {
                    b.HasOne("digitalAgency.Domain.Entities.BlogCategory", "BlogCategories")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategories");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("digitalAgency.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("digitalAgency.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("digitalAgency.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
